site_name: Robotic Watch App Docs
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
nav:
  - Home: index.md
  - API Reference: reference.md